version: "3.2"
services:

  project:
    restart: always
    container_name: code
    environment:
      SECRET_KEY: ${SECRET_KEY}
    command : bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
  
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
   
