# Generated by Django 4.0.1 on 2022-01-19 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.date(2022, 1, 19))),
                ('time', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('issue', models.TextField()),
                ('existing', models.BooleanField(default=False)),
            ],
        ),
    ]
