name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./backend
  
    steps:
    - uses: actions/checkout@v2
    - name: setting up docker_username and password
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PWD: ${{secrets.DOCKER_PWD}}

      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PWD
    
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/rachna_healthcare .
    - name: Pushing the image to docker hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/rachna_healthcare 


